baseURL = "https://azurey0.github.io/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Ran"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

#enable chinese readtime
hasCJKLanguage = true

[params]
title = "I'm Zhang Ran"
author = "张然"
description = "张然的个人站"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = ["css/custom.css","css/styles.css"]
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

## Math settings
[params.math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/azurey0"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:zhangr235@mail2.sysu.edu.cn"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

